import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Kenny Tye</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar
        navItemLeft="Resume"
        navItemsRight={{
          itemOne: 'About',
          itemTwo: 'Projects',
          itemThree: 'Contact',
        }}
      />
      <Footer />
    </div>
  );
};

export default Home;
