import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import Footer from '../components/Footer';
import Introduction from '../components/Introduction';
import LinkFooter from '../components/LinkFooter';
import AboutMe from '../components/AboutMe';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';
import Contact from '../components/Contact';
import Projects from '../components/Projects';
import OrbsContainer from '../components/OrbsContainer';

const Home: NextPage = () => {
  const [isMobile, setIsMobile] = useState(false);

  // Listen for the window size
  useEffect(() => {
    if (window.innerWidth <= 576) {
      setIsMobile(true);
    }
    function handleMobileResize() {
      if (window.innerWidth <= 576) {
        setIsMobile(true);
      }
      if (window.innerWidth > 576) {
        setIsMobile(false);
      }
    }
    window.addEventListener('resize', handleMobileResize);
  }, [isMobile]);

  return (
    <div className={styles.main}>
      <Head>
        <title>Kenny Tye</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <OrbsContainer />
      <Navbar
        navItemLeft="Resume"
        navItemsRight={{
          itemOne: 'About',
          itemTwo: 'Projects',
          itemThree: 'Contact',
        }}
        isMobile={isMobile}
      />
      <Introduction />
      <AboutMe />
      <Projects />
      <Contact />
      <LinkFooter />
      <Footer />
    </div>
  );
};

export default Home;
